spring:
  application:
    name: socialmedia
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eju?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 100MB


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sns.socialmedia.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){green} %clr(%-5level) %clr(${PID:-}){magenta} %clr(---){faint} [socialmedia] %clr(%logger - %M{10}){cyan} - %msg%n)"
  level:
    root: INFO
    com.sns.socialmedia: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG
    org.mybatis.spring.SqlSessionTemplate: DEBUG
    org.springframework.jdbc.datasource: DEBUG

jwt:
  secret: YzEyMzR0bXZxQzRmNTZ2cEFoUGVpMWdIajU3aWdoZ2g
  expiration: 3600000

profile:
  upload:
    dir: C:\File

